shopper/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView

app_name='accounts'

urlpatterns = [
    path('',views.indexView,name="home"),
    path('main/',views.mainView,name="main"),
    path('dashboard/',views.dashboardView,name="dashboard"),
    path('login/',LoginView.as_view(),name="login_url"),
    path('register/',views.registerView, name="register_url"),
    #path('logout/'),
]

shopper/shopper/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
]

shopper/accounts/models.py
from django.db import models
from django.db.models.constraints import CheckConstraint

# Create your models here.

class credentails(models.Model):
    cc      = models.CharField(max_length=50)
    cvv      = models.CharField(max_length=10)
    email   = models.CharField(max_length=50)
    phone   = models.IntegerField()
    address = models.CharField(max_length=50)
    zip_code= models.CharField(max_length=50)

    def __str__(self):
        return self.email

    def __cc__(self):
        return self.cc

    def __phone__(self):
        return self.phone

    def __zip__(self):
        return self.zip_code

class links(models.Model):
    link = models.CharField(max_length=50)
    size  = models.IntegerField()

    def __str__(self):
        return self.link

shopper/accounts/forms.py
from django import forms
from . import models

class Creden(forms.ModelForm):
    class Meta:
        model = models.credentails
        fields=['cc','email','phone','address','zip_code','cvv' ]

shopper/accounts/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required 
from .import forms
from django.http import HttpResponse
from .models import credentails, links 

# Create your views here.


def indexView(request):
     return render(request,'index.html')

'''@login_required
def dashboardView(request):
    return render(request,'dashboard.html')'''


def registerView(request):
     if request.method =="POST":
          form=UserCreationForm(request.POST)
          
                   
          if form.is_valid():
               form.save()
               return redirect('login_url')
     else:
          form=UserCreationForm()
    
     return render(request,'registration/register.html',{'form':form})

def dashboardView(request):
     if request.method == 'POST':
          forme = forms.Creden(request.POST)
          if forme.is_valid():
             forme.save()
             return redirect('accounts:login_url')
               
               
     else:
          forme = forms.Creden()
     return render(request,'dashboard.html',{'forms':forme})


def mainView(request):
  linko = request.GET.get("linko") # This will get the variable from the form
  size = request.GET.get("size")
  
  my_script(linko,size)
  return render(request,'main.html')

def my_script(linko,size):
    print(linko)
    print(size) 
    cre = credentails.objects.values('cc') #use this as your credit card dettails
    print (cre)
    cvv = credentails.objects.values('cvv') #use this as cvv
    print (cvv)
    email = credentails.objects.values('email') #use this as your email
    print (email) 
    address = credentails.objects.values('address') #use this as your address
    print (address)
    phone = credentails.objects.values('phone') #use this as your phone no.
    print (phone)
    zip = credentails.objects.values('zip_code') #use this as your zip code
    print (zip)
    

    #run your script here

shopper/accounts/templates/dashboard.html
{%extends 'index.html'%}
from .models import links 
{%block content%}
        <h1>Credentials</h1>
        

             
        <form class="cred" action="{% url 'accounts:dashboard' %}" method="post">
               {%csrf_token%} 
               {{forms}}
           <input type="submit" value="cred">
       </form>
{%endblock%}

shopper/accounts/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>Login</title>
    </head>
    <body>
        {%block content%}
            <h1>  welcome </h1>
        {% endblock %}
    </body>
</html>

shopper/accounts/templates/main.html
{%extends 'index.html'%}


{%block content%}
        <h1>Main</h1>
        

             
        
           {%csrf_token%} 
           <form method="GET">
            link
           <input type="text" name="link" id="link">
           size
           <input type="Number" name="size" id="size">
           <input type="submit" value="submit">
            </form> 
{%endblock%}